### ISSUE TITLE
Usage svgo to make the SVGs smaller

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-platform/eclipse.platform.common#111]
[svgo](https://github.com/svg/svgo) is a cool to to minify SVG files (by e.g. removing invisible objects).
Let's use this to squeeze some bytes out of all the SVGs used in documentations

**Comment by mickaelistria** [comment]
I don't think it's necessarily good everywhere: svgo seems like a binary format; no metadata, no comments... Basically an svgo file becomes harder to maintain than a plain SVG which might embed useful information beyond the payload. So to use svgo, I think we need to make sure we'll never want to modify the SVG files, and that's not always true.

**Comment by mickaelistria** [comment]
ok

**Comment by BeckerWdf** [comment]
> How much "space" do we actually save?

SVGs get smaller around 20% in average. So it's not too much.

**Comment by BeckerWdf** [comment]
> The originals of these SVGs are stored in the platform images repo. So we don't need to change the SVGs directly in this repo. So I think we can do this optimisation.

See https://github.com/eclipse-platform/eclipse.platform.images/pull/8
