### ISSUE TITLE
Consider automating optimizing(lossless) images for size

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.common#14]
https://github.com/marketplace/imgbot sounds like a good solution to do the trick for us.

**Comment by akurtakov** [comment]
@sravanlakkimsetti  wdyt?

**Comment by akurtakov** [comment]
@vogella did anything happen?

**Comment by vogella** [comment]
> @vogella did anything happen?

I got no PR for the images

**Comment by akurtakov** [comment]
OK, I give up on this one.
