### ISSUE TITLE
Javadoc error in I20220731-1600 and later

### ISSUE THREAD

**Issue by vik-chand** [eclipse-platform/eclipse.platform.common#56]
See https://download.eclipse.org/eclipse/downloads/drops4/I20220731-1900/compilelogs/jdt.doc.isv.javadoc.txt

javadoc: error - Error reading file: ../org.eclipse.platform.doc.isv/reference/api/element-list
1 error

This also results in 30MB reduction of eclipse SDK download.

**Comment by vik-chand** [comment]
Javadoc error are gone but still the eclipse SDK is 218MB instead of around 250MB. Is this some optimization or does it reflect something is missing?

**Comment by iloveeclipse** [comment]
There is still error while javadoc generation.
Test fails on alll platforms:
https://download.eclipse.org/eclipse/downloads/drops4/I20220801-1800/testresults/html/org.eclipse.ua.tests.doc_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html
`org.eclipse.ua.tests.doc.internal.linkchecker.TocLinkChecker | testPlatformIsvGenerated`

**Comment by akurtakov** [comment]
There is no error in javadoc generation (can be seen in https://download.eclipse.org/eclipse/downloads/drops4/I20220801-1800/logs.php#javadoc ) but doc bundles have to be touched so the newly built ones are published. I'll do it now.

**Comment by akurtakov** [comment]
Should be done with https://github.com/eclipse-platform/eclipse.platform.common/commit/ab32d06c85f9fe20851c82126f4f77c246f9a9f4 . If someone thinks it's worth a rebuild say so and I'll start a new I-build.

**Comment by mickaelistria** [comment]
Seems fixed in latest I-Build.
