### ISSUE TITLE
Update Migration Guide for Platform and JDT for 4.25

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.common#65]
Migration guide links are incorrect in the welcome page. They have to be updated for 4.25

**Comment by vogella** [comment]
Would be nice to not open issues for such short-term tasks, followed a few minutes by a PR, as these issues increase my inbox traffic without adding value.

**Comment by ktatavarthi** [comment]
> Would be nice to not open issues for such short-term tasks, followed a few minutes by a PR, as these issues increase my inbox traffic without adding value.

This Issues has multiple PRs spanning across multiple repositories associated with fixing it. so, the need for an issue.

**Comment by vogella** [comment]
> This Issues has multiple PRs spanning across multiple repositories associated with fixing it. so, the need for an issue.

OK
